2024-12-30 13:53:52,847 - ERROR - Unexpected error during registration: Install 'email_validator' for email validation support.
Stack Trace:
Stack (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/werkzeug/serving.py", line 390, in handle
    super().handle()
  File "/usr/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/werkzeug/serving.py", line 325, in execute
    for data in application_iter:
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/werkzeug/debug/__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/bacancy/Development/flask_app/DropConnect/routes/auth_route.py", line 17, in registration
    return register.register_user()
  File "/home/bacancy/Development/flask_app/DropConnect/views/register.py", line 44, in register_user
    error_logger.log_error(f"Unexpected error during registration: {str(e)}")
  File "/home/bacancy/Development/flask_app/DropConnect/loggers/error_logger.py", line 39, in log_error
    self._logger.error(
Stack (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.10/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.10/socketserver.py", line 747, in __init__
    self.handle()
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/werkzeug/serving.py", line 390, in handle
    super().handle()
  File "/usr/lib/python3.10/http/server.py", line 433, in handle
    self.handle_one_request()
  File "/usr/lib/python3.10/http/server.py", line 421, in handle_one_request
    method()
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/werkzeug/serving.py", line 362, in run_wsgi
    execute(self.server.app)
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/werkzeug/serving.py", line 325, in execute
    for data in application_iter:
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/werkzeug/debug/__init__.py", line 330, in debug_application
    app_iter = self.app(environ, start_response)
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/flask/app.py", line 1488, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/bacancy/Development/flask_app/venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/bacancy/Development/flask_app/DropConnect/routes/auth_route.py", line 17, in registration
    return register.register_user()
  File "/home/bacancy/Development/flask_app/DropConnect/views/register.py", line 44, in register_user
    error_logger.log_error(f"Unexpected error during registration: {str(e)}")
  File "/home/bacancy/Development/flask_app/DropConnect/loggers/error_logger.py", line 39, in log_error
    self._logger.error(
